CREATE TABLE DEPARTAMENTOS
(
ID INTEGER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY (ID)
);

CREATE TABLE CIUDADES
(
ID INTEGER NOT NULL,
DEPARTAMENTOS_ID INTEGER NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
CONSTRAINT CIUDADES_PK PRIMARY KEY (ID),
CONSTRAINT FK_CIUDADES_DEPARTAMENTOS FOREIGN KEY (DEPARTAMENTOS_ID) REFERENCES DEPARTAMENTOS(ID)
);

CREATE TABLE CODIGOS_POSTAL
(
ID INTEGER NOT NULL,
CIUDADES_ID INTEGER NOT NULL,
CONSTRAINT CODIGOS_POSTAL_PK PRIMARY KEY (ID),
CONSTRAINT FK_CODIGOS_POSTAL_CIUDADES FOREIGN KEY (CIUDADES_ID) REFERENCES CIUDADES(ID)
);

CREATE TABLE CLIENTES 
(
ID INTEGER NOT NULL,
CUIDAD_ID INTEGER NOT NULL,
TIPO_DOCUMENTO VARCHAR2(50) NOT NULL,
IDENTIFICACION VARCHAR2(20) NOT NULL,
NOMBRES VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(150) NOT NULL,
DIRECCION_2 VARCHAR2(150) NULL,
CELULAR VARCHAR2(50) NOT NULL,
CONSTRAINT CLIENTES_PK PRIMARY KEY (ID),
CONSTRAINT FK_CLIENTES_CIUDAD FOREIGN KEY (CUIDAD_ID) REFERENCES CODIGOS_POSTAL(ID),
CONSTRAINT CHK_TIPO_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('CEDULA DE CIUDADANIA','PASAPORTE','CEDULA DE EXTRANJERIA','NIT'))
);

CREATE TABLE EMPLEADOS 
(
ID INTEGER NOT NULL,
JEFE_ID INTEGER NOT NULL,
TIPO_DOCUMENTO VARCHAR2(50) NOT NULL,
IDENTIFICACION VARCHAR2(20) NOT NULL,
NOMBRES VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(150) NOT NULL,
CARGO VARCHAR2(50) NOT NULL,
SALARIO VARCHAR2(50) NOT NULL,
CONSTRAINT EMPLEADOS_PK PRIMARY KEY (ID),
CONSTRAINT FK_EMPLEADOS_JEFE FOREIGN KEY (JEFE_ID) REFERENCES EMPLEADOS(ID),
CONSTRAINT CHK_TIPO_DOCUMENTO_EMPLEADOS CHECK (TIPO_DOCUMENTO IN ('CEDULA DE CIUDADANIA','PASAPORTE','CEDULA DE EXTRANJERIA'))
);

CREATE TABLE CENTRO_CARGAS 
(
ID INTEGER NOT NULL,
ENCARGADO_ID INTEGER NOT NULL,
CODIGOS_POSTAL_ID INTEGER NOT NULL,
NOMBRES VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(150) NOT NULL,
TELEFONO VARCHAR2(50) NOT NULL,
CONSTRAINT CENTRO_CARGAS_PK PRIMARY KEY (ID),
CONSTRAINT FK_CENTRO_CARGAS_CODIGOS_POSTAL FOREIGN KEY (CODIGOS_POSTAL_ID) REFERENCES CODIGOS_POSTAL(ID),
CONSTRAINT FK_CENTRO_CARGAS_EMPLEADO FOREIGN KEY (ENCARGADO_ID) REFERENCES EMPLEADOS(ID)

);


CREATE TABLE VEHICULOS
(
ID INTEGER NOT NULL,
CENTRO_CARGAS_ID INTEGER NOT NULL,
MARCA VARCHAR2(50) NOT NULL,
MODELO VARCHAR2(50) NOT NULL,
LINEA VARCHAR2(50) NOT NULL,
TIPO_COMBUSTIBLE VARCHAR2(50) NOT NULL,
KILOMETRAJE NUMBER NOT NULL,
CAPACIDAD VARCHAR2(50) NOT NULL,
CONSTRAINT VEHICULOS_PK PRIMARY KEY (ID),
CONSTRAINT CHK_TIPO_COMBUSTIBLE CHECK (TIPO_COMBUSTIBLE IN ('DIESEL','GASOLINA')),
CONSTRAINT FK_VEHICULOS_CENTRO_CARGAS FOREIGN KEY (CENTRO_CARGAS_ID) REFERENCES CENTRO_CARGAS(ID),
CONSTRAINT CHK_CAPACIDAD CHECK (CAPACIDAD IN ('2,5 TON','2,8 TON','3,3 TON','3,5 TON','5 TON','6 TON','11 TON','700 KG'))
);

CREATE TABLE MANTENIMIENTOS
(
ID INTEGER NOT NULL,
TIPO_MANTENIMIENTO VARCHAR2(50) NOT NULL,
CONSTRAINT MANTENIMIENTOS_PK PRIMARY KEY (ID),
CONSTRAINT CHK_TIPO_MANTENIMIENTO 
CHECK (TIPO_MANTENIMIENTO IN ('5000 KILOMETROS','10,000 KILOMETROS','20,000 KILOMETROS','40,000 KILOMETROS','50,000 KILOMETROS','100,000 KILOMETROS'))
);

CREATE TABLE MANTENIMIENTO_ITEMS
(
ID INTEGER NOT NULL,
NOMBRE VARCHAR2(150) NOT NULL,
CONSTRAINT MANTENIMIENTO_ITEMS_PK PRIMARY KEY (ID)
);

CREATE TABLE DETALLE_MANTENIMIENTOS
(
ID INTEGER NOT NULL,
MANTENIMIENTO_ID INTEGER NOT NULL,
MANTENIMIENTO_ITEM_ID INTEGER NOT NULL,
CONSTRAINT DETALLE_MANTENIMIENTOS_PK PRIMARY KEY (ID),
CONSTRAINT FK_DETALLE_MANT_MANTENIMIENTO FOREIGN KEY (MANTENIMIENTO_ID) REFERENCES MANTENIMIENTOS(ID),
CONSTRAINT FK_DETALLE_MANT_MANTENIMIENTO_ITEMS FOREIGN KEY (MANTENIMIENTO_ITEM_ID) REFERENCES MANTENIMIENTO_ITEMS(ID)
);

CREATE TABLE PROGRAMACION_MANTENIMIENTOS
(
ID INTEGER NOT NULL,
MANTENIMIENTO_ID INTEGER NOT NULL,
EMPLEADOS_ID INTEGER NOT NULL,
INVENTARIO_VEHICULOS_ID INTEGER NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PROGRAMACION_MANTENIMIENTOS_PK PRIMARY KEY (ID),
CONSTRAINT FK_PROG_MANTENIMIENTO_MANTENIMIENTO FOREIGN KEY (MANTENIMIENTO_ID) REFERENCES MANTENIMIENTOS(ID),
CONSTRAINT FK_PROG_MANTENIMIENTO_EMPLEADOS FOREIGN KEY (EMPLEADOS_ID) REFERENCES EMPLEADOS(ID),
CONSTRAINT FK_PROG_MANTENIMIENTO_VEHICULOS FOREIGN KEY (INVENTARIO_VEHICULOS_ID) REFERENCES VEHICULOS(ID)
);


CREATE TABLE DETALLE_PROGRAMACION_MANTENIMIENTOS
(
ID INTEGER NOT NULL,
PROGRAMACION_MANTENIMIENTOS_ID INTEGER NOT NULL,
DETALLE_MANTENIMIENTOS_ID INTEGER NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
OBSERVACION VARCHAR2(250),
CONSTRAINT DETALLE_PROGRAMACION_MANTENIMIENTOS_PK PRIMARY KEY (ID),
CONSTRAINT CHK_ESTADO CHECK (ESTADO IN ('REALIZADO','PENDIENTE','NO REALIZADO')),
CONSTRAINT FK_DET_PROG_MANT_PROG_MANTENIMIENTO FOREIGN KEY (PROGRAMACION_MANTENIMIENTOS_ID) REFERENCES PROGRAMACION_MANTENIMIENTOS(ID),
CONSTRAINT FK_DET_PROG_MANT_DETA_MANTENIMIENTO FOREIGN KEY (DETALLE_MANTENIMIENTOS_ID) REFERENCES DETALLE_MANTENIMIENTOS(ID)
);



CREATE TABLE DESPACHOS
(
ID INTEGER NOT NULL,
CLIENTES_ID INTEGER NOT NULL,
ANCHO NUMBER NOT NULL,
LARGO NUMBER NOT NULL,
ALTO NUMBER NOT NULL,
PESO NUMBER NOT NULL,
CIUDAD_ORIGEN_ID INTEGER NOT NULL,
CIUDAD_DESTINO_ID INTEGER NOT NULL,
PESO_VOLUMEN NUMBER NOT NULL,
TIPO_SERVICIO VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(250) NOT NULL,
FECHA_DESPACHO DATE NOT NULL,
HORA_DESPACHO VARCHAR2(50) NOT NULL,
FECHA_ENTREGA DATE,
HORA_ENTREGA VARCHAR2(50),
OBSERVACION VARCHAR2(250),
UNIDADES NUMBER NOT NULL,
FLETE_FIJO NUMBER NOT NULL,
FLETE_VARIABLE NUMBER NOT NULL,
OTROS NUMBER NOT NULL,
VALOR_SERVICIO NUMBER NOT NULL,
CONSTRAINT DESPACHOS_PK PRIMARY KEY (ID),
CONSTRAINT CHK_TIPO_SERVICIO CHECK (TIPO_SERVICIO IN ('CARGA AEREA','MERCANCIA','MENSAJERIA','FIRMA DE DOCUMENTOS','RADICACION DE DOCUMENTOS')),
CONSTRAINT FK_DESPACHO_CLIENTES FOREIGN KEY (CLIENTES_ID) REFERENCES CLIENTES(ID),
CONSTRAINT FK_DESPACHO_CIUDADES FOREIGN KEY (CIUDAD_ORIGEN_ID) REFERENCES CODIGOS_POSTAL(ID),
CONSTRAINT FK_DESPACHO2_CIUDADES FOREIGN KEY (CIUDAD_DESTINO_ID) REFERENCES CODIGOS_POSTAL(ID)
);

CREATE TABLE SEGUIMIENTOS
(
ID INTEGER NOT NULL,
DESPACHOS_ID INTEGER NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
FECHA DATE NOT NULL,
HORA VARCHAR2(50) NOT NULL,
CONSTRAINT SEGUIMIENTOS_PK PRIMARY KEY (ID),
CONSTRAINT CHK_ESTADO_SEGUIMIENTOS CHECK (ESTADO IN ('A RECIBIR','EN TERMINAL ORIGEN','EN TRANSPORTE','EN TERMINAL DESTINO','EN REPARTO','ENTREGADA')),
CONSTRAINT FK_SEGUIMIENTOS_DESPACHOS FOREIGN KEY (DESPACHOS_ID) REFERENCES DESPACHOS(ID)
);

CREATE TABLE COTIZACION 
(
ID INTEGER NOT NULL,
CENTRO_CARGAS_ID INTEGER NOT NULL,
CIUDAD_DESTINO_ID INTEGER NOT NULL,
PRECIO_KILO DECIMAL,
CONSTRAINT COTIZACION_PK PRIMARY KEY(ID),
CONSTRAINT FK_COTIZACION_CENTROSCARGA FOREIGN KEY (CENTRO_CARGAS_ID) REFERENCES CENTRO_CARGAS(ID),
CONSTRAINT FK_COTIZACION_CIUDADES FOREIGN KEY (CIUDAD_DESTINO_ID) REFERENCES CODIGOS_POSTAL(ID)
);


